CREATE TABLE [dbo].[Account] (
    [AccountId]                     INT             NOT NULL,
    [AccountNumber]                 CHAR (8)        NOT NULL,
    [AccountName]                   NVARCHAR (100)  NOT NULL,
    [ProductCategoryId]             TINYINT         NOT NULL,
    [AdvertiserCustomerId]          INT             NOT NULL,
    [AgencyCustomerId]              INT             NULL,
    [SalesHouseCustomerId]          INT             NULL,
    [BillToCustomerId]              INT             NOT NULL,
    [PreferredBillToPaymentInstrId] INT             NULL,
    [CountryCode]                   CHAR (2)        NOT NULL,
    [FinancialStatusId]             TINYINT         NOT NULL,
    [LifeCycleStatusId]             TINYINT         NOT NULL,
    [LockStatusId]                  TINYINT         NOT NULL,
    [PreferredUserId]               INT             NOT NULL,
    [PreferredCurrencyId]           SMALLINT        NOT NULL,
    [PreferredLanguageId]           SMALLINT        NOT NULL,
    [AgencyContactName]             NVARCHAR (100)  NULL,
    [SoldToPaymentInstrId]          INT             NULL,
    [OtherAddressId]                INT             NULL,
    [BillingComment]                NVARCHAR (1000) NULL,
    [PaymentOptionId]               TINYINT         NULL,
    [NetTerm]                       TINYINT         NULL,
    [CompressBillingFlag]           BIT             NOT NULL,
    [SpendLimitId]                  SMALLINT        NOT NULL,
    [CreatedDTim]                   DATETIME        NOT NULL,
    [ModifiedDTim]                  DATETIME        NOT NULL,
    [ModifiedByUserId]              INT             NOT NULL,
    [Timestamp]                     BINARY (8)      NULL,
    [BillingRetryID]                SMALLINT        NULL,
    [BillingRetryDtim]              DATETIME        NULL,
    [BillingSuccessCount]           INT             NULL,
    [AgencyCommissionPct]           DECIMAL (5, 2)  NULL,
    [SalesHouseCommissionPct]       DECIMAL (5, 2)  NULL,
    [CompressedBilling]             TINYINT         NULL,
    [PauseStatus]                   TINYINT         NULL,
    [PUID]                          BIGINT          NULL,
    [NotificationFlagBitmask]       SMALLINT        NOT NULL,
    [AccountTypeId]                 TINYINT         NOT NULL,
    [TimeZoneId]                    TINYINT         NULL,
    [CashbackTypeId]                TINYINT         NOT NULL,
    [CreatedUTCDateTime]            DATETIME        NOT NULL,
    [AnalyticsOptInId]              TINYINT         NULL,
    [TimeStamp2]                    BINARY (8)      NULL,
    [BackupPaymentInstrId]          INT             NULL,
    [LastFinStatusUpdatedEntityId]  SMALLINT        NULL
);

