CREATE TABLE [dbo].[Customer] (
    [CustomerId]                INT            NOT NULL,
    [Name]                      NVARCHAR (100) NOT NULL,
    [CustomerTypeId]            TINYINT        NOT NULL,
    [ServiceLevelId]            TINYINT        NOT NULL,
    [IndustryId]                SMALLINT       NOT NULL,
    [IsLocal]                   BIT            NOT NULL,
    [FinancialStatusId]         TINYINT        NOT NULL,
    [LifeCycleStatusId]         TINYINT        NOT NULL,
    [LockStatusId]              TINYINT        NOT NULL,
    [ModifiedByUserId]          INT            NULL,
    [CreatedDTim]               DATETIME       CONSTRAINT [Customer_CreatedDTim_UTC_DF] DEFAULT (getutcdate()) NOT NULL,
    [ModifiedDTim]              DATETIME       CONSTRAINT [Customer_ModifiedDTim_UTC_DF] DEFAULT (getutcdate()) NOT NULL,
    [Timestamp]                 BINARY (8)     CONSTRAINT [Customer_TimeStamp_DF] DEFAULT (@@dbts) NOT NULL,
    [TrustRatingId]             INT            NULL,
    [MonthlyAnniversaryDay]     TINYINT        NULL,
    [MarketId]                  TINYINT        NOT NULL,
    [SystemLimitLevelID]        SMALLINT       NOT NULL,
    [ReportServiceLevelId]      TINYINT        NOT NULL,
    [NotificationFlagBitmask]   SMALLINT       NOT NULL,
    [IsTPAN]                    BIT            CONSTRAINT [Customer_IsTPAN_DF] DEFAULT ((0)) NOT NULL,
    [CustomerNumber]            CHAR (10)      NULL,
    [FraudStatusId]             TINYINT        CONSTRAINT [Customer_FraudStatusId_DF] DEFAULT ((6)) NOT NULL,
    [ContactInfoId]             INT            NULL,
    [TimeStamp2]                BINARY (8)     CONSTRAINT [Customer_TimeStamp2_DF] DEFAULT (@@dbts) NULL,
    [CreditLimit]               MONEY          NULL,
    [ManagedByPartnerId]        INT            NULL,
    [FraudReasonCodeId]         TINYINT        NULL,
    [FraudStatusChangeDateTime] DATETIME       NULL
);

